# Generated by Django 3.1.1 on 2021-02-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='participants',
            new_name='participant',
        ),
    ]
